version: '3'
services:
  server:
    build: .
    ports:
      - '8081:8081'
    links:
      - mongo:my_database
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

